name: Pragma

on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup cargo registry
        run: |
          mkdir -p ~/.cargo
          cat >> ~/.cargo/config.toml << 'EOF'
          [registries.pragma]
          index = "sparse+https://registry.production.pragma.build/api/v1/crates/"
          EOF
      - name: Build
        run: cargo build --release
